#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source /Users/at/.zshrc.local

export PATH="$HOME/.rbenv/bin:$PATH"
#eval "$(rbenv init -)"
# no rehash makes it faster
eval "$(rbenv init - --no-rehash)"

# added by travis gem
[ -f /Users/at/.travis/travis.sh ] && source /Users/at/.travis/travis.sh
